# Generated by Django 4.2.10 on 2024-03-05 10:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_article_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publish_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Время публикации'),
        ),
    ]
